id: A99E11E10
title: Guru Yoga of the Great Tertön Pema Lingpa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:17:24.918986
  last_modified_at: 2022-03-01 01:17:24.918992
